version: "3.8"

# Development environment override
services:

  database:
    ports:
      - '5432:5432'

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - symfony
