version: "3.8"

services:
  php:
    build:
      target: php_dev


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - symfony

  database:
    ports:
      - '5432:5432'

  web:
    build:
      context: frontend
      target: dev-envs
    depends_on:
      - php
    ports:
      - '4200:4200'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/project
      - /project/node_modules